name: sdrop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.23.0
  - scikit-learn>=1.2.0
  - joblib>=1.2.0
  - matplotlib>=3.6.0
  - netcdf4>=1.6.0
  - numba>=0.58.0  # Added for performance optimization
  - pandas
  - tqdm>=4.66.0  # Added for progress bars
  - h5py
  - pip

